### ISSUE TITLE
Yazi 0.2.5 release unsupported

### ISSUE THREAD

**Issue by miyoku157** [KKV9/compress.yazi#4]
Hi,

I don't use lua that much so i don't really know what's happening. But after i install the init.lua file and try to archive a folder (or files).
I Got this error message: 
```
Micro plugin failed:
runtime error: [string "/build/source/yazi-plugin/src/isolate/entry.r..."]:12: attempt to call a nil value (field 'target_os')
stack traceback:
	[C]: in field 'target_os'
	[string "/build/source/yazi-plugin/src/isolate/entry.r..."]:12: in main chunk
```

**Comment by KKV9** [comment]
Hi, can you tell me what version of yazi you are using?

**Comment by miyoku157** [comment]
Yazi 0.2.5

**Comment by KKV9** [comment]
The plugin is not supported on this version currently. Please update to a later version.

**Comment by KKV9** [comment]
I updated the plugin to allow it to run on the current release version of yazi. Let me know if it works for you @miyoku157

**Comment by miyoku157** [comment]
I was able to create a tar and zip file, so it's working :)
