### ISSUE TITLE
Support busybox

### ISSUE THREAD

**Issue by Brixy** [KKV9/compress.yazi#5]
Thank for you script.

It would be great, if busybox's `tar` command (see below) was supported. Busybox is used by Alpine Linux. (Yet, the GNU `tar` script can easily be installed with Alpine's package manager.)

This is what I tried:

```
if is_command_available("busybox") then
	local archive_commands = {
		["%.tar.gz$"] = { command = "tar", args = { "c", "-z" }, compress = "gzip", compress_args = { "-f", output_name } },
	}
end
```

But I'm not sure, how `archive_cmd`, `archive_args`, `archive_compress` and `archive_compress_args` play together.

It would be great if you could point me in the right direction. Then I could open a PR, if you want.

The busybox tar command for creating a gzip archive looks like this:

```
tar c -z -f out.tar.gz *
```

Thanks a lot.

<details>
<summary>busybox tar</summary>

```
BusyBox v1.36.1 (2024-06-10 15:30:53 UTC) multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [LONGOPT]... [FILE]...

Create, extract, or list files from a tar file

	c	Create
	x	Extract
	t	List
	-f FILE	Name of TARFILE ('-' for stdin/out)
	-C DIR	Change to DIR before operation
	-v	Verbose
	-O	Extract to stdout
	-m	Don't restore mtime
	-o	Don't restore user:group
	-k	Don't replace existing files
	-Z	(De)compress using compress
	-z	(De)compress using gzip
	-J	(De)compress using xz
	-j	(De)compress using bzip2
	--lzma	(De)compress using lzma
	-a	(De)compress based on extension
	-h	Follow symlinks
	-T FILE	File with names to include
	-X FILE	File with glob patterns to exclude
	--exclude PATTERN	Glob pattern to exclude
	--overwrite		Replace existing files
	--strip-components NUM	NUM of leading components to strip
	--no-recursion		Don't descend in directories
	--numeric-owner		Use numeric user:group
	--no-same-permissions	Don't restore access permissions
```

</details>

**Comment by KKV9** [comment]
Hi, thanks for your interest. The script currently relies on the `-r` or append option of `tar` and is also supported by posix. Looking at the options you provided, busybox tar doesn't have the append option. Unfortunately, this means adapting the script for busybox is not trivial.
If you want to attempt this yourself, investigate how to append to a tar archive using only busybox and create a function for it.

**Comment by Brixy** [comment]
I see. Thank for your explanation.

As I am not eloqent enough in Lua and this use case is a bit alien, maybe this issue should be closed?!

Anyway, I'll dabble a bit, and in case of success, I'll happily submit a PR.

Thanks for your great tool!
